# Generated by Django 5.1.7 on 2025-06-05 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_ads', models.BooleanField(default=False, help_text='Enable advertising on the site')),
                ('ad_provider', models.CharField(choices=[('none', 'None'), ('adsense', 'Google AdSense'), ('media_net', 'Media.net'), ('amazon', 'Amazon Associates'), ('taboola', 'Taboola'), ('outbrain', 'Outbrain'), ('custom', 'Custom Ad Code')], default='none', help_text='Select your primary ad provider', max_length=20)),
                ('adsense_client_id', models.CharField(blank=True, help_text='Google AdSense Client ID (e.g., ca-pub-XXXXXXXXXXXXXXXX)', max_length=50)),
                ('enable_auto_ads', models.BooleanField(default=False, help_text='Enable Google Auto Ads')),
                ('media_net_cid', models.CharField(blank=True, help_text='Media.net Customer ID', max_length=50)),
                ('amazon_tracking_id', models.CharField(blank=True, help_text='Amazon Associates Tracking ID', max_length=50)),
                ('custom_ad_script', models.TextField(blank=True, help_text='Custom ad provider script (for header)')),
                ('enable_header_ads', models.BooleanField(default=False, help_text='Show ads in header area')),
                ('enable_sidebar_ads', models.BooleanField(default=True, help_text='Show ads in sidebar')),
                ('enable_in_content_ads', models.BooleanField(default=True, help_text='Show ads within content')),
                ('enable_footer_ads', models.BooleanField(default=False, help_text='Show ads in footer area')),
                ('in_content_ad_frequency', models.IntegerField(default=3, help_text='Show in-content ad every N paragraphs (0 to disable)')),
                ('max_ads_per_page', models.IntegerField(default=5, help_text='Maximum number of ads per page')),
                ('disable_ads_for_logged_in', models.BooleanField(default=False, help_text="Don't show ads to logged-in users")),
                ('lazy_load_ads', models.BooleanField(default=True, help_text='Lazy load ads for better performance')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Advertising Settings',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_provider', models.CharField(choices=[('none', 'None'), ('google', 'Google Analytics'), ('plausible', 'Plausible Analytics'), ('matomo', 'Matomo'), ('umami', 'Umami'), ('custom', 'Custom Script')], default='none', help_text='Select your analytics provider', max_length=20)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics Measurement ID (e.g., G-XXXXXXXXXX)', max_length=20)),
                ('google_analytics_v4', models.BooleanField(default=True, help_text='Use Google Analytics 4 (GA4)')),
                ('plausible_domain', models.CharField(blank=True, help_text='Your domain as configured in Plausible', max_length=255)),
                ('plausible_script_url', models.URLField(blank=True, default='https://plausible.io/js/script.js', help_text='Plausible script URL (for self-hosted instances)')),
                ('matomo_url', models.URLField(blank=True, help_text='Your Matomo instance URL')),
                ('matomo_site_id', models.CharField(blank=True, help_text='Matomo Site ID', max_length=10)),
                ('umami_script_url', models.URLField(blank=True, help_text='Umami script URL')),
                ('umami_website_id', models.CharField(blank=True, help_text='Umami Website ID', max_length=50)),
                ('custom_analytics_script', models.TextField(blank=True, help_text='Paste your custom analytics script here (including <script> tags)')),
                ('enable_anonymize_ip', models.BooleanField(default=True, help_text='Anonymize visitor IP addresses')),
                ('respect_do_not_track', models.BooleanField(default=False, help_text='Respect Do Not Track browser setting')),
                ('enable_cookie_consent', models.BooleanField(default=True, help_text='Show cookie consent banner')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Analytics Settings',
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_consent_message', models.TextField(default='We use cookies to improve your experience and analyze site traffic. By continuing, you agree to our use of cookies.', help_text='Message shown in cookie consent banner')),
                ('cookie_consent_button_text', models.CharField(default='Accept', help_text='Text for the accept button', max_length=50)),
                ('cookie_consent_link_text', models.CharField(default='Learn more', help_text='Text for the privacy policy link', max_length=50)),
                ('enable_gdpr_features', models.BooleanField(default=True, help_text='Enable GDPR compliance features')),
                ('allow_cookie_preferences', models.BooleanField(default=True, help_text='Allow users to manage cookie preferences')),
                ('privacy_policy_page', models.ForeignKey(blank=True, help_text='Link to privacy policy page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Privacy Settings',
            },
        ),
    ]
